language: go
go:
  - 1.x
env:
  - DEP_VERSION="v0.4.1"
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - dep ensure
stages:
  - test
jobs:
  include:
  - stage: test
    script: make test
